"""config table

Revision ID: 19df90465a2b
Revises: e0c830e0de52
Create Date: 2020-02-09 11:27:22.934612

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '19df90465a2b'
down_revision = 'e0c830e0de52'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('config',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('key', sa.String(length=32), nullable=False),
    sa.Column('val', sa.String(length=4096), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', 'key', name='config_user_key_key')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('config')
    # ### end Alembic commands ###
