"""user.default_equity_account_id

Revision ID: 25f0788d5998
Revises: 57da2deda526
Create Date: 2019-12-01 17:46:42.207291

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '25f0788d5998'
down_revision = '57da2deda526'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('default_equity_account_id', sa.Integer(), nullable=True))
    op.create_foreign_key('user_default_equity_account_id_fkey', 'user', 'account', ['default_equity_account_id'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('user_default_equity_account_id_fkey', 'user', type_='foreignkey')
    op.drop_column('user', 'default_equity_account_id')
    # ### end Alembic commands ###
