"""m1_portfolio: name

Revision ID: b45790a64147
Revises: b879e9664c5e
Create Date: 2019-11-26 15:47:55.219782

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b45790a64147'
down_revision = 'b879e9664c5e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('m1_portfolio', sa.Column('name', sa.String(), server_default='', nullable=False))
    op.create_unique_constraint('m1_portfolio_name_date_key', 'm1_portfolio', ['name', 'date'])
    op.drop_constraint('m1_portfolio_date_key', 'm1_portfolio', type_='unique')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint('m1_portfolio_date_key', 'm1_portfolio', ['date'])
    op.drop_constraint('m1_portfolio_name_date_key', 'm1_portfolio', type_='unique')
    op.drop_column('m1_portfolio', 'name')
    # ### end Alembic commands ###
