"""m1_finance.cost_basis

Revision ID: e0c830e0de52
Revises: d4266249b278
Create Date: 2020-01-30 22:58:42.892836

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e0c830e0de52'
down_revision = 'd4266249b278'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('m1_portfolio', sa.Column('cost_basis', sa.Float(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('m1_portfolio', 'cost_basis')
    # ### end Alembic commands ###
