"""entry.pending

Revision ID: e4dbda83b5c3
Revises: 25f0788d5998
Create Date: 2019-12-07 21:19:53.346354

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e4dbda83b5c3'
down_revision = '25f0788d5998'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('entry', sa.Column('pending', sa.Boolean(), nullable=False))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('entry', 'pending')
    # ### end Alembic commands ###
